-- MySQL Script generated by MySQL Workbench
-- 2016年12月22日 星期四 11时48分39秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema product
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `product` ;

-- -----------------------------------------------------
-- Schema product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `product` DEFAULT CHARACTER SET gbk ;
USE `product` ;

-- -----------------------------------------------------
-- Table `product`.`syslog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`syslog` ;

CREATE TABLE IF NOT EXISTS `product`.`syslog` (
  `syslog_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `u_id` VARCHAR(50) NOT NULL DEFAULT '无' COMMENT '操作者',
  `uip` VARCHAR(255) NOT NULL DEFAULT '无',
  `request_uri` VARCHAR(255) NOT NULL DEFAULT '无' COMMENT '请求URI',
  `params` TEXT NULL COMMENT '操作提交的数据',
  `remark` VARCHAR(255) NULL COMMENT '日志备注',
  `user_agent` VARCHAR(255) NULL DEFAULT NULL COMMENT '用户代理',
  `method` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作方式',
  `exception` TEXT NULL DEFAULT NULL COMMENT '异常信息',
  PRIMARY KEY (`syslog_id`),
  INDEX `idx_syslog_uid` (`u_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '管理员日志表';


-- -----------------------------------------------------
-- Table `product`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`menu` ;

CREATE TABLE IF NOT EXISTS `product`.`menu` (
  `menu_id` INT(11) NOT NULL COMMENT '编号',
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `isactive` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '激活标记',
  `sort` INT(11) NOT NULL DEFAULT 100 COMMENT '排序',
  `href` VARCHAR(2000) NOT NULL DEFAULT '无' COMMENT '跳转视图',
  `icon` VARCHAR(100) NULL DEFAULT NULL COMMENT '图标',
  `is_show` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否在菜单中显示',
  `permission` VARCHAR(50) NULL DEFAULT NULL COMMENT '权限标识sys:menu:edit',
  `create_by` VARCHAR(50) NOT NULL COMMENT '创建者',
  `create_date` DATETIME NOT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NOT NULL COMMENT '更新者',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL COMMENT '备注信息',
  PRIMARY KEY (`menu_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `product`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`role` ;

CREATE TABLE IF NOT EXISTS `product`.`role` (
  `r_id` INT(11) NOT NULL COMMENT '编号',
  `r_name` VARCHAR(30) NOT NULL COMMENT '角色名称',
  `isactive` TINYINT(1) NOT NULL DEFAULT TRUE COMMENT '是否有效',
  `data_scope` INT(11) NOT NULL DEFAULT 99 COMMENT '操作范围',
  `r_type` VARCHAR(20) NOT NULL DEFAULT '无' COMMENT '角色类型',
  `remarks` VARCHAR(255) NOT NULL DEFAULT '无' COMMENT '备注信息',
  `create_user` VARCHAR(50) NOT NULL COMMENT '创建',
  `create_date` DATETIME NOT NULL COMMENT '创建时间',
  `update_user` VARCHAR(64) NOT NULL,
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE INDEX `r_name_UNIQUE` (`r_name` ASC),
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `product`.`role_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`role_menu` ;

CREATE TABLE IF NOT EXISTS `product`.`role_menu` (
  `role_id` INT(11) NOT NULL COMMENT '角色编号',
  `menu_id` INT(11) NOT NULL COMMENT '菜单编号',
  PRIMARY KEY (`role_id`, `menu_id`),
  INDEX `idx_role` (`role_id` ASC),
  INDEX `idx_menu` (`menu_id` ASC),
  CONSTRAINT `fk_rm_menu`
    FOREIGN KEY (`menu_id`)
    REFERENCES `product`.`menu` (`menu_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `product`.`role` (`r_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '角色-菜单';


-- -----------------------------------------------------
-- Table `product`.`duty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`duty` ;

CREATE TABLE IF NOT EXISTS `product`.`duty` (
  `u_id` VARCHAR(50) NOT NULL,
  `u_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(64) NULL,
  `isactive` TINYINT(1) NOT NULL DEFAULT TRUE COMMENT '是否可登录或禁止',
  `photo` VARCHAR(200) NOT NULL DEFAULT 'defaultpic' COMMENT '用户头像',
  `email` VARCHAR(50) NOT NULL DEFAULT '无' COMMENT '邮箱',
  `mobile` VARCHAR(50) NOT NULL DEFAULT '无' COMMENT '手机',
  `remark` VARCHAR(255) NOT NULL DEFAULT '无' COMMENT '备注信息',
  `login_ip` VARCHAR(50) NOT NULL DEFAULT '无' COMMENT '登陆IP',
  `login_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登陆时间',
  `expire_date` DATETIME NULL COMMENT '到期时间',
  `create_date` DATETIME NOT NULL COMMENT '创建时间',
  `last_update` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近更新',
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `product`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product`.`user_role` ;

CREATE TABLE IF NOT EXISTS `product`.`user_role` (
  `user_id` VARCHAR(50) NOT NULL COMMENT '用户编号',
  `role_id` INT(11) NOT NULL COMMENT '角色编号',
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_role_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_ur_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `product`.`duty` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ur_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `product`.`role` (`r_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COMMENT = '用户-角色';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `product`.`duty`
-- -----------------------------------------------------
START TRANSACTION;
USE `product`;
INSERT INTO `product`.`duty` (`u_id`, `u_name`, `password`, `isactive`, `photo`, `email`, `mobile`, `remark`, `login_ip`, `login_date`, `expire_date`, `create_date`, `last_update`) VALUES ('1', 'ww', '123', DEFAULT, 'rrrrr', 'rrrrrrrrrrrr', DEFAULT, 'gg', '556', '1967:1:1 9:9:9', NULL, '1967:1:1 9:9:9', '1967:1:1 9:9:9');

COMMIT;

